// Site-wide configuration loader.
// To customize the site, edit: site/config.json
// Do NOT edit this file unless you are a developer.

import type { SiteConfig } from './SiteConfig.types'
import rawConfig from '../../site/config.json'

const AppConfig: SiteConfig = {
    ...(rawConfig as SiteConfig),
    // Allow CI/deployment to override the site URL via env var
    siteUrl: process.env.NEXT_PUBLIC_SITE_URL || rawConfig.siteUrl,
}

export default AppConfig
